// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ChampionsLeagueTickets.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace ChampionsLeagueTickets.Domain.Data;

public partial class ChampionsLeagueDbContext : DbContext
{
    public ChampionsLeagueDbContext(DbContextOptions<ChampionsLeagueDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Club> Clubs { get; set; }

    public virtual DbSet<Match> Matches { get; set; }

    public virtual DbSet<StadiumSection> Stadiumsections { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Club>(entity =>
        {
            entity.ToTable("clubs");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Match>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_match");

            entity.ToTable("matches");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Awayteam).HasColumnName("awayteam");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.Hometeam).HasColumnName("hometeam");

            entity.HasOne(d => d.AwayteamNavigation).WithMany(p => p.MatchAwayteamNavigations)
                .HasForeignKey(d => d.Awayteam)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_Away_Team");

            entity.HasOne(d => d.HometeamNavigation).WithMany(p => p.MatchHometeamNavigations)
                .HasForeignKey(d => d.Hometeam)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Match_Home_Team");
        });

        modelBuilder.Entity<StadiumSection>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_stadiumvakken_1");

            entity.ToTable("stadiumsections");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.HomeTeam).HasColumnName("homeTeam");
            entity.Property(e => e.Location)
                .IsRequired()
                .HasMaxLength(4)
                .IsFixedLength()
                .HasColumnName("location");
            entity.Property(e => e.Ring)
                .IsRequired()
                .HasMaxLength(5)
                .IsFixedLength()
                .HasColumnName("ring");
            entity.Property(e => e.Seats).HasColumnName("seats");

            entity.HasOne(d => d.HomeTeamNavigation).WithMany(p => p.Stadiumsections)
                .HasForeignKey(d => d.HomeTeam)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Stadiumvakken_Home_Team");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}