// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChampionsLeagueTickets.Domain.Entities;

public partial class Club
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool Sellable { get; set; }

    public int? CityId { get; set; }

    public virtual ICollection<Match> MatchAwayteamNavigations { get; set; } = new List<Match>();

    public virtual ICollection<Match> MatchHometeamNavigations { get; set; } = new List<Match>();

    public virtual ICollection<Stadiumsection> Stadiumsections { get; set; } = new List<Stadiumsection>();
}