// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChampionsLeagueTickets.Domain.Entities;

public partial class Match
{
    public int Id { get; set; }

    public int Hometeam { get; set; }

    public int Awayteam { get; set; }

    public DateOnly Date { get; set; }

    public virtual Club AwayteamNavigation { get; set; }

    public virtual Club HometeamNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}