// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChampionsLeagueTickets.Domain.Entities;

public partial class Orderline
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int TicketId { get; set; }

    public virtual Ticket IdNavigation { get; set; }

    public virtual Order Order { get; set; }
}