// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChampionsLeagueTickets.Domain.Entities;

public partial class Order
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public DateOnly Date { get; set; }

    public virtual ICollection<Orderline> Orderlines { get; set; } = new List<Orderline>();

    public virtual AspNetUser User { get; set; }
}