// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChampionsLeagueTickets.Domain.Entities;

public partial class SeasonTicket
{
    public int Id { get; set; }

    public int ClubId { get; set; }

    public int SectionId { get; set; }

    public decimal Price { get; set; }

    public string UserId { get; set; }

    public virtual Club Club { get; set; }

    public virtual StadiumSection Section { get; set; }

    public virtual AspNetUser User { get; set; }
}