// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChampionsLeagueTickets.Domain.Entities;

public partial class StadiumSection
{
    public int Id { get; set; }

    public int HomeTeam { get; set; }

    public string Ring { get; set; }

    public string Location { get; set; }

    public int Seats { get; set; }

    public virtual Club HomeTeamNavigation { get; set; }
}