// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChampionsLeagueTickets.Domain.Entities;

public partial class Ticket
{
    public int Id { get; set; }

    public string Code { get; set; }
    public int SectionId { get; set; }

    public decimal Price { get; set; }

    public string Status { get; set; }

    public int? MatchId { get; set; }

    public string Type { get; set; }

    public string UserId { get; set; }

    public virtual Match Match { get; set; }

    public virtual Orderline Orderline { get; set; }

    public virtual StadiumSection Section { get; set; }

    public virtual AspNetUser User { get; set; }
}